// Regenerates src/version.ts from package.json. Runs as part of `npm run build`
// so the published artifact always carries the version being released.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
writeFileSync(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by scripts/write-version.mjs — do not edit.\nexport const SDK_VERSION = "${pkg.version}";\n`,
);
console.log(`src/version.ts -> ${pkg.version}`);
